version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    commit-message:
      prefix: "chore(deps):"
      prefix-minor: "chore(deps):"
      prefix-major: "chore(deps):"
    pull-request-branch-name:
      separator: "/"
